#!/bin/sh

#g++ -std=c++11 -o Analyse_BI_ToHist.exe Analyse_BI_ToHist.C BeamLineClasses/class_AcquisitionXBPF.C BeamLineClasses/class_AcquisitionXBTF.C BeamLineClasses/class_Detector.C BeamLineClasses/class_BeamLine.C BeamLineClasses/class_DetectorCoincidences.C BeamLineClasses/unpack.C BeamLineClasses/plotting.C `root-config --cflags --glibs`
#g++ -std=c++11 -o Analyse_BL_ToHist.exe Analyse_BL_ToHist.C BeamLineClasses/class_AcquisitionXBPF.C BeamLineClasses/class_AcquisitionXBTF.C BeamLineClasses/class_Detector.C BeamLineClasses/class_BeamLine.C BeamLineClasses/class_DetectorCoincidences.C BeamLineClasses/unpack.C BeamLineClasses/plotting.C `root-config --cflags --glibs`
#g++ -std=c++11 -o Analyse_BIBL_ToHist.exe Analyse_BIBL_ToHist.C BeamLineClasses/class_AcquisitionXBPF.C BeamLineClasses/class_AcquisitionXBTF.C BeamLineClasses/class_Detector.C BeamLineClasses/class_BeamLine.C BeamLineClasses/class_DetectorCoincidences.C BeamLineClasses/unpack.C BeamLineClasses/plotting.C `root-config --cflags --glibs`
#g++ -std=c++11 -o Analyse_BI_ToTree.exe Analyse_BI_ToTree.C BeamLineClasses/class_AcquisitionXBPF.C BeamLineClasses/class_AcquisitionXBTF.C BeamLineClasses/class_Detector.C BeamLineClasses/class_BeamLine.C BeamLineClasses/class_DetectorCoincidences.C BeamLineClasses/unpack.C BeamLineClasses/plotting.C `root-config --cflags --glibs`
#g++ -std=c++11 -o Analyse_BL_ToTree.exe Analyse_BL_ToTree.C BeamLineClasses/class_AcquisitionXBPF.C BeamLineClasses/class_AcquisitionXBTF.C BeamLineClasses/class_Detector.C BeamLineClasses/class_BeamLine.C BeamLineClasses/class_DetectorCoincidences.C BeamLineClasses/unpack.C BeamLineClasses/plotting.C `root-config --cflags --glibs`
#g++ -std=c++11 -o Analyse_BIBL_ToTree.exe Analyse_BIBL_ToTree.C BeamLineClasses/class_AcquisitionXBPF.C BeamLineClasses/class_AcquisitionXBTF.C BeamLineClasses/class_Detector.C BeamLineClasses/class_BeamLine.C BeamLineClasses/class_DetectorCoincidences.C BeamLineClasses/unpack.C BeamLineClasses/plotting.C `root-config --cflags --glibs`
g++ -std=c++11 -o Analyse_BIBL_ToHistToTree.exe Analyse_BIBL_ToHistToTree.C BeamLineClasses/class_AcquisitionXBPF.C BeamLineClasses/class_AcquisitionXBTF.C BeamLineClasses/class_Detector.C BeamLineClasses/class_BeamLine.C BeamLineClasses/class_DetectorCoincidences.C BeamLineClasses/unpack.C BeamLineClasses/plotting.C `root-config --cflags --glibs`
